"""chnaged thje corrected_file default to true

Revision ID: cb57dc290698
Revises: 5fc41d7f9337
Create Date: 2025-08-30 21:49:38.636677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb57dc290698'
down_revision: Union[str, Sequence[str], None] = '5fc41d7f9337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'original_file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'original_file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
